sudo: true
language: node_js
os:
  - linux
  - osx
before_script:
  - npm install
before_install:
  - sudo chmod +x ./test/deploy.sh
install:
  - if [[ $TRAVIS_OS_NAME == linux ]]; then sudo ./test/deploy.sh; fi;
node_js:
  - '6'
  - '5'
  - '4'
addons:
  apt:
    packages:
      - libpng-dev
      - zlib1g-dev